/-
# Clifford circuit syntax and denotational semantics.

We define a small inductive type `Cliff1` for single-qubit Clifford circuits
(generated by `H` and `S`), and `Cliff2` for two-qubit Clifford circuits
(generated by `H` on either qubit, `S` on either qubit, and `CNOT(0,1)`).

The denotational semantics `denote1 / denote2` interpret a circuit as a
unitary matrix (`Op 2` or `Op 4`); they agree with the QMeas compiler's
gadget compositions up to Pauli-frame corrections (see `Soundness.lean`).
-/
import QMeas.Pauli

namespace QMeas

/-! ### Single-qubit Cliffords -/

inductive Cliff1 where
  /-- Identity. -/
  | id : Cliff1
  /-- Hadamard. -/
  | H  : Cliff1
  /-- Phase gate. -/
  | S  : Cliff1
  /-- Sequential composition: `seq c1 c2` means apply c1 then c2. -/
  | seq : Cliff1 → Cliff1 → Cliff1
  deriving Repr

namespace Cliff1

/-- Denotational semantics: a single-qubit Clifford circuit is a 2×2 matrix
    over ℂ.  Composition is matrix multiplication (right operand applied
    first). -/
noncomputable def denote : Cliff1 → Op 2
  | .id        => I2
  | .H         => H_gate
  | .S         => S_gate
  | .seq c1 c2 => (denote c2) * (denote c1)

end Cliff1

/-! ### Two-qubit Cliffords

We extend the single-qubit syntax with the two-qubit `CNOT` and qubit-indexed
single-qubit gates.  `idx : Fin 2` selects which qubit the gate acts on
(0 = control/first, 1 = target/second).
-/

inductive Cliff2 where
  | id   : Cliff2
  | H    (i : Fin 2) : Cliff2
  | S    (i : Fin 2) : Cliff2
  | CNOT : Cliff2          -- always control = qubit 0, target = qubit 1
  | seq  : Cliff2 → Cliff2 → Cliff2
  deriving Repr

namespace Cliff2

/-- Lift a single-qubit gate to act on qubit 0 of a 2-qubit system: `U ⊗ I`. -/
noncomputable def lift0 (U : Op 2) : Op 4 := kron2 U I2

/-- Lift a single-qubit gate to act on qubit 1 of a 2-qubit system: `I ⊗ U`. -/
noncomputable def lift1 (U : Op 2) : Op 4 := kron2 I2 U

noncomputable def denote : Cliff2 → Op 4
  | .id        => I4
  | .H ⟨0, _⟩  => lift0 H_gate
  | .H ⟨1, _⟩  => lift1 H_gate
  | .H ⟨n+2, h⟩ => absurd h (by omega)
  | .S ⟨0, _⟩  => lift0 S_gate
  | .S ⟨1, _⟩  => lift1 S_gate
  | .S ⟨n+2, h⟩ => absurd h (by omega)
  | .CNOT      => QMeas.CNOT
  | .seq c1 c2 => (denote c2) * (denote c1)

end Cliff2

end QMeas
