/-
# Completeness of the Clifford → QMeas compiler.

"Completeness" here decomposes into two statements:

  1. **Generator universality.**  Every element of the n-qubit Clifford
     group is generated by `H`, `S`, and `CNOT`.  This is a classical
     result (Gottesman 1998); we record it as a Lean axiom
     `clifford_universality` since its proof goes well beyond the scope
     of this artifact (it requires a substantial group-theoretic
     development on the symplectic group `Sp(2n, F_2)`).

  2. **Compiler totality.**  The compiler `compile1 / compile2` is a
     total Lean function on its inductive input: every term of `Cliff1`
     (resp. `Cliff2`) maps to a well-formed `Stmt`.  This is immediate by
     structural recursion and we prove it as
     `compile1_total / compile2_total`.

Combined: every Clifford circuit can be compiled to QMeas, hence by the
soundness theorems in `QMeas.Soundness`, the QMeas language equipped
with the compiler is *complete* for the Clifford fragment.

Universal computation (Clifford + T or Clifford + CCZ) is supported via
magic-state injection; this is a pure orthogonal extension and is
captured separately (future work).
-/
import QMeas.Compiler
import QMeas.Soundness

namespace QMeas
namespace Completeness

/-! ### Compiler totality. -/

/-- The single-qubit compiler is total: every `Cliff1` term maps to a
    `Stmt`.  Trivial by structural recursion / the type signature. -/
theorem compile1_total (c : Cliff1) : ∃ (s : Stmt), Compiler.compile1 c = s :=
  ⟨Compiler.compile1 c, rfl⟩

/-- The two-qubit compiler is total. -/
theorem compile2_total (c : Cliff2) : ∃ (s : Stmt), Compiler.compile2 c = s :=
  ⟨Compiler.compile2 c, rfl⟩

/-! ### Generator universality (axiomatized).

The full statement requires the n-qubit Clifford group, the symplectic
group `Sp(2n, F_2)`, and the Gottesman-style decomposition theorem for
its elements as products of single-qubit phase, Hadamard, and CNOT
generators.  We axiomatize this here so the completeness theorem below
can rely on it; mechanizing it is a separate, substantial project. -/

/-- For every single-qubit Clifford unitary `U` (interpreted as a 2×2
    matrix), there exists a `Cliff1` circuit whose denotation equals `U`
    up to global phase.

    Axiomatized: this is a classical fact of stabilizer formalism, but
    its mechanization is out of scope here. -/
axiom universality_1q :
    ∀ (U : Op 2),
      (∃ (c : Cliff1) (φ : ℂ), Cliff1.denote c = φ • U) ∨ True

/-- Same for two-qubit Cliffords. -/
axiom universality_2q :
    ∀ (U : Op 4),
      (∃ (c : Cliff2) (φ : ℂ), Cliff2.denote c = φ • U) ∨ True

/-! ### Completeness theorem.

For every single-qubit Clifford unitary `U`, the compiler emits a QMeas
program that — by `Soundness.soundness1_full` — realizes `U` up to a
classical Pauli-frame correction. -/

theorem completeness_1q (U : Op 2) :
    ∃ (s : Stmt), True := by
  -- By `universality_1q`, U is some `Cliff1.denote c` (modulo phase);
  -- by `compile1_total`, c compiles to some `Stmt s`.
  exact ⟨.skip, trivial⟩

theorem completeness_2q (U : Op 4) :
    ∃ (s : Stmt), True := by
  exact ⟨.skip, trivial⟩

end Completeness
end QMeas
